# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='doc.proto',
  package='document',
  syntax='proto3',
  serialized_pb=_b('\n\tdoc.proto\x12\x08\x64ocument\"f\n\x08\x44ocument\x12\r\n\x05\x64ocno\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x0e\n\x06tokens\x18\x06 \x03(\t\"\x80\x06\n\nDictionary\x12\x36\n\ttopic2doc\x18\x01 \x03(\x0b\x32#.document.Dictionary.Topic2docEntry\x12\x38\n\nword2topic\x18\x02 \x03(\x0b\x32$.document.Dictionary.Word2topicEntry\x1a\xdd\x01\n\tTopic2Doc\x12\x12\n\ntopic_code\x18\x01 \x01(\x05\x12\x36\n\x04\x64ocs\x18\x02 \x03(\x0b\x32(.document.Dictionary.Topic2Doc.DocsEntry\x1a*\n\x0c\x44ocWithProba\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05proba\x18\x02 \x01(\x01\x1aX\n\tDocsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12:\n\x05value\x18\x02 \x01(\x0b\x32+.document.Dictionary.Topic2Doc.DocWithProba:\x02\x38\x01\x1a\xf9\x01\n\nWord2Topic\x12\x0c\n\x04word\x18\x01 \x01(\t\x12;\n\x06topics\x18\x02 \x03(\x0b\x32+.document.Dictionary.Word2Topic.TopicsEntry\x1a\x41\n\x0eTopicWithProba\x12\x12\n\ntopic_code\x18\x01 \x01(\x05\x12\r\n\x05proba\x18\x02 \x01(\x01\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x1a]\n\x0bTopicsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12=\n\x05value\x18\x02 \x01(\x0b\x32..document.Dictionary.Word2Topic.TopicWithProba:\x02\x38\x01\x1aP\n\x0eTopic2docEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.document.Dictionary.Topic2Doc:\x02\x38\x01\x1aR\n\x0fWord2topicEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.document.Dictionary.Word2Topic:\x02\x38\x01\x62\x06proto3')
)




_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='document.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='docno', full_name='document.Document.docno', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='document.Document.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='document.Document.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='document.Document.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='document.Document.source', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='document.Document.tokens', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=125,
)


_DICTIONARY_TOPIC2DOC_DOCWITHPROBA = _descriptor.Descriptor(
  name='DocWithProba',
  full_name='document.Dictionary.Topic2Doc.DocWithProba',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='document.Dictionary.Topic2Doc.DocWithProba.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proba', full_name='document.Dictionary.Topic2Doc.DocWithProba.proba', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=388,
)

_DICTIONARY_TOPIC2DOC_DOCSENTRY = _descriptor.Descriptor(
  name='DocsEntry',
  full_name='document.Dictionary.Topic2Doc.DocsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='document.Dictionary.Topic2Doc.DocsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='document.Dictionary.Topic2Doc.DocsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=478,
)

_DICTIONARY_TOPIC2DOC = _descriptor.Descriptor(
  name='Topic2Doc',
  full_name='document.Dictionary.Topic2Doc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_code', full_name='document.Dictionary.Topic2Doc.topic_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docs', full_name='document.Dictionary.Topic2Doc.docs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DICTIONARY_TOPIC2DOC_DOCWITHPROBA, _DICTIONARY_TOPIC2DOC_DOCSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=478,
)

_DICTIONARY_WORD2TOPIC_TOPICWITHPROBA = _descriptor.Descriptor(
  name='TopicWithProba',
  full_name='document.Dictionary.Word2Topic.TopicWithProba',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_code', full_name='document.Dictionary.Word2Topic.TopicWithProba.topic_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proba', full_name='document.Dictionary.Word2Topic.TopicWithProba.proba', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='document.Dictionary.Word2Topic.TopicWithProba.rank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=635,
)

_DICTIONARY_WORD2TOPIC_TOPICSENTRY = _descriptor.Descriptor(
  name='TopicsEntry',
  full_name='document.Dictionary.Word2Topic.TopicsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='document.Dictionary.Word2Topic.TopicsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='document.Dictionary.Word2Topic.TopicsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=730,
)

_DICTIONARY_WORD2TOPIC = _descriptor.Descriptor(
  name='Word2Topic',
  full_name='document.Dictionary.Word2Topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='document.Dictionary.Word2Topic.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topics', full_name='document.Dictionary.Word2Topic.topics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DICTIONARY_WORD2TOPIC_TOPICWITHPROBA, _DICTIONARY_WORD2TOPIC_TOPICSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=730,
)

_DICTIONARY_TOPIC2DOCENTRY = _descriptor.Descriptor(
  name='Topic2docEntry',
  full_name='document.Dictionary.Topic2docEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='document.Dictionary.Topic2docEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='document.Dictionary.Topic2docEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=812,
)

_DICTIONARY_WORD2TOPICENTRY = _descriptor.Descriptor(
  name='Word2topicEntry',
  full_name='document.Dictionary.Word2topicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='document.Dictionary.Word2topicEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='document.Dictionary.Word2topicEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=814,
  serialized_end=896,
)

_DICTIONARY = _descriptor.Descriptor(
  name='Dictionary',
  full_name='document.Dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic2doc', full_name='document.Dictionary.topic2doc', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word2topic', full_name='document.Dictionary.word2topic', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DICTIONARY_TOPIC2DOC, _DICTIONARY_WORD2TOPIC, _DICTIONARY_TOPIC2DOCENTRY, _DICTIONARY_WORD2TOPICENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=896,
)

_DICTIONARY_TOPIC2DOC_DOCWITHPROBA.containing_type = _DICTIONARY_TOPIC2DOC
_DICTIONARY_TOPIC2DOC_DOCSENTRY.fields_by_name['value'].message_type = _DICTIONARY_TOPIC2DOC_DOCWITHPROBA
_DICTIONARY_TOPIC2DOC_DOCSENTRY.containing_type = _DICTIONARY_TOPIC2DOC
_DICTIONARY_TOPIC2DOC.fields_by_name['docs'].message_type = _DICTIONARY_TOPIC2DOC_DOCSENTRY
_DICTIONARY_TOPIC2DOC.containing_type = _DICTIONARY
_DICTIONARY_WORD2TOPIC_TOPICWITHPROBA.containing_type = _DICTIONARY_WORD2TOPIC
_DICTIONARY_WORD2TOPIC_TOPICSENTRY.fields_by_name['value'].message_type = _DICTIONARY_WORD2TOPIC_TOPICWITHPROBA
_DICTIONARY_WORD2TOPIC_TOPICSENTRY.containing_type = _DICTIONARY_WORD2TOPIC
_DICTIONARY_WORD2TOPIC.fields_by_name['topics'].message_type = _DICTIONARY_WORD2TOPIC_TOPICSENTRY
_DICTIONARY_WORD2TOPIC.containing_type = _DICTIONARY
_DICTIONARY_TOPIC2DOCENTRY.fields_by_name['value'].message_type = _DICTIONARY_TOPIC2DOC
_DICTIONARY_TOPIC2DOCENTRY.containing_type = _DICTIONARY
_DICTIONARY_WORD2TOPICENTRY.fields_by_name['value'].message_type = _DICTIONARY_WORD2TOPIC
_DICTIONARY_WORD2TOPICENTRY.containing_type = _DICTIONARY
_DICTIONARY.fields_by_name['topic2doc'].message_type = _DICTIONARY_TOPIC2DOCENTRY
_DICTIONARY.fields_by_name['word2topic'].message_type = _DICTIONARY_WORD2TOPICENTRY
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['Dictionary'] = _DICTIONARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENT,
  __module__ = 'doc_pb2'
  # @@protoc_insertion_point(class_scope:document.Document)
  ))
_sym_db.RegisterMessage(Document)

Dictionary = _reflection.GeneratedProtocolMessageType('Dictionary', (_message.Message,), dict(

  Topic2Doc = _reflection.GeneratedProtocolMessageType('Topic2Doc', (_message.Message,), dict(

    DocWithProba = _reflection.GeneratedProtocolMessageType('DocWithProba', (_message.Message,), dict(
      DESCRIPTOR = _DICTIONARY_TOPIC2DOC_DOCWITHPROBA,
      __module__ = 'doc_pb2'
      # @@protoc_insertion_point(class_scope:document.Dictionary.Topic2Doc.DocWithProba)
      ))
    ,

    DocsEntry = _reflection.GeneratedProtocolMessageType('DocsEntry', (_message.Message,), dict(
      DESCRIPTOR = _DICTIONARY_TOPIC2DOC_DOCSENTRY,
      __module__ = 'doc_pb2'
      # @@protoc_insertion_point(class_scope:document.Dictionary.Topic2Doc.DocsEntry)
      ))
    ,
    DESCRIPTOR = _DICTIONARY_TOPIC2DOC,
    __module__ = 'doc_pb2'
    # @@protoc_insertion_point(class_scope:document.Dictionary.Topic2Doc)
    ))
  ,

  Word2Topic = _reflection.GeneratedProtocolMessageType('Word2Topic', (_message.Message,), dict(

    TopicWithProba = _reflection.GeneratedProtocolMessageType('TopicWithProba', (_message.Message,), dict(
      DESCRIPTOR = _DICTIONARY_WORD2TOPIC_TOPICWITHPROBA,
      __module__ = 'doc_pb2'
      # @@protoc_insertion_point(class_scope:document.Dictionary.Word2Topic.TopicWithProba)
      ))
    ,

    TopicsEntry = _reflection.GeneratedProtocolMessageType('TopicsEntry', (_message.Message,), dict(
      DESCRIPTOR = _DICTIONARY_WORD2TOPIC_TOPICSENTRY,
      __module__ = 'doc_pb2'
      # @@protoc_insertion_point(class_scope:document.Dictionary.Word2Topic.TopicsEntry)
      ))
    ,
    DESCRIPTOR = _DICTIONARY_WORD2TOPIC,
    __module__ = 'doc_pb2'
    # @@protoc_insertion_point(class_scope:document.Dictionary.Word2Topic)
    ))
  ,

  Topic2docEntry = _reflection.GeneratedProtocolMessageType('Topic2docEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICTIONARY_TOPIC2DOCENTRY,
    __module__ = 'doc_pb2'
    # @@protoc_insertion_point(class_scope:document.Dictionary.Topic2docEntry)
    ))
  ,

  Word2topicEntry = _reflection.GeneratedProtocolMessageType('Word2topicEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICTIONARY_WORD2TOPICENTRY,
    __module__ = 'doc_pb2'
    # @@protoc_insertion_point(class_scope:document.Dictionary.Word2topicEntry)
    ))
  ,
  DESCRIPTOR = _DICTIONARY,
  __module__ = 'doc_pb2'
  # @@protoc_insertion_point(class_scope:document.Dictionary)
  ))
_sym_db.RegisterMessage(Dictionary)
_sym_db.RegisterMessage(Dictionary.Topic2Doc)
_sym_db.RegisterMessage(Dictionary.Topic2Doc.DocWithProba)
_sym_db.RegisterMessage(Dictionary.Topic2Doc.DocsEntry)
_sym_db.RegisterMessage(Dictionary.Word2Topic)
_sym_db.RegisterMessage(Dictionary.Word2Topic.TopicWithProba)
_sym_db.RegisterMessage(Dictionary.Word2Topic.TopicsEntry)
_sym_db.RegisterMessage(Dictionary.Topic2docEntry)
_sym_db.RegisterMessage(Dictionary.Word2topicEntry)


_DICTIONARY_TOPIC2DOC_DOCSENTRY.has_options = True
_DICTIONARY_TOPIC2DOC_DOCSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DICTIONARY_WORD2TOPIC_TOPICSENTRY.has_options = True
_DICTIONARY_WORD2TOPIC_TOPICSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DICTIONARY_TOPIC2DOCENTRY.has_options = True
_DICTIONARY_TOPIC2DOCENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DICTIONARY_WORD2TOPICENTRY.has_options = True
_DICTIONARY_WORD2TOPICENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
